name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # If needed
          fetch-depth: 0

      - name: Resolve symlinks
        run: |
          mkdir resolved_docs
          rsync -aL docs/ resolved_docs/
          # -aL option resolves symlinks

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./resolved_docs

